// <!DOCTYPE html>
// <html lang="en">
// <head>
//     <meta charset="UTF-8">
//     <meta name="viewport" content="width=device-width, initial-scale=1.0">
//     <title>Document</title>
// </head>
// <body>
//     <div id=cities_table></div>
   
   
// </body>
{/* <script> */}

    var id_c=100;
    var cities = [
"Antwerp", 
"Aberdeen",
"Augsburg",
"Alexandroupolis",
"Athens",
"Alicante",
"Almeria",
"Aalborg",
"Aarhus",
"Ancona",
"Aosta",
"Amsterdam",
"Alanya",
"Ankara",
"Antalya",
"Altenrhein",
"Brussels",
"Burgas",
"Banja Luka",
"Belfast",
"Birmingham",
"Bournemouth",
"Bristol",
"Budapest",
"Berlin",
"Braunschweig-Wolfsburg",
"Bremen",
"Billund",
"Barcelona",
"Bilbao",
"Bologna",
"Bergen",
"Bodo",
"BydgoszczIgnacy",
"Bucharest",
"Belgrade",
"Bratislava",
"Bordeaux",
"Bol",
"Brno",
"Basel",
"Bern",
"Cardiff",
"Cambridge",
"Coventry",
"Cologne",
"Corfu",
"Copenhagen",
"Cordoba",
"Connemara",
"Cork",
"Cagliari-Elmas",
"Catania",
"Cluj-Napoca",
"Clermont-Ferrand",
"Chambery-Savoie",
"Cherbourg",
"Durham",
"Doncaster",
"Dortmund",
"Dresden",
"Duesseldorf",
"Dublin",
"Dalaman",
"Dubrovnik",
"East Midlands",
"Edinburgh",
"Exeter",
"Erfurt",
"Esbjerg",
"Ercan",
"Eilat",
"Eindhoven",
"Engadin",
"Frankfurt",
"Friedrichshafen",
"Fuerteventura",
"Florence",
"Floro",
"Faro",
"Funchal",
"Graz",
"Gorna Oryahovitsa",
"Guernsey",
"Glasgow",
"Gloucestershire",
"Granada",
"Girona",
"Galway",
"Genoa",
"Groningen",
"Gdansk",
"Geneva",
"Gothenburg",
"Humberside",
"Heviz-Balaton",
"Hamburg",
"Hannover",
"Heringsdorf",
"Hof-Plauen",
"Heraklion",
"Helsinki",
"Innsbruck",
"Inverness",
"Isle Of Man",
"Ibiza",
"Izmir",
"Istanbul",
"Jonkoping",
"Klagenfurt",
"Karlsruhe",
"Kortrijk-Wevelgem",
"Kaunas",
"Katowice",
"Krakow",
"Kosice",
"Karlovy Vary",
"Karlstad",
"Kuressaare",
"Linz",
"Liege",
"Land's End",
"Liverpool",
"Lydd",
"Leeds",
"London",
"Luebeck",
"Lanzarote",
"Las Palmas de Gran Canaria",
"Lleida-Alguaire",
"Lamezia",
"Larnaca",
"Liepaja",
"Luxembourg",
"Lelystad",
"Lisbon",
"Ljubljana",
"Lappeenranta",
"Le Touquet",
"Lille",
"Lyon",
"Lugano",
"Lulea",
"Manchester",
"Mannheim",
"Memmingen",
"Muenster",
"Munich",
"Madrid",
"Malaga",
"Mahon",
"Murcia",
"Milan",
"Malta",
"Monte Carlo",
"Maastricht",
"Moss",
"Milas",
"Mariehamn",
"Marseille",
"Metz",
"Montpellier",
"Malmo",
"Norwich",
"Newcastle",
"Newquay",
"Nuremberg",
"Naples",
"Nis Constantinet",
"Nantes",
"Nice",
"Norrkoping",
"Ostend",
"Alderney",
"Oviedo",
"Olbia Costa",
"Ohrid",
"Oslo",
"Osijek",
"Ostrava",
"Plovdiv",
"Plymouth",
"Paderborn",
"Rostock",
"Palmade",
"Palermo",
"Pescara",
"Pisa",
"Paphos",
"Palanga",
"Ponta Delgada",
"Porto",
"Poprad",
"Paris",
"Pula",
"Podgorica",
"Pardubice",
"Prague",
"Parnu",
"Rhodes",
"Reykjavik",
"Reus",
"Rijeka",
"Rome",
"Rimini",
"Riga",
"Rotterdam",
"Ronneby",
"Salzburg",
"Sofia",
"Sarajevo",
"Southampton",
"Swansea",
"Shoreham",
"Siegerland",
"Saarbruecken",
"Stuttgart",
"Santorini",
"Shannon",
"Salamanca",
"Santiagode Compostela",
"Sevilla",
"Siauliai",
"Skopje",
"Sandefjord",
"Stavanger",
"Strasbourg",
"Split",
"Sion",
"Stockholm",
"Tirana",
"Thessaloniki",
"Tenerife",
"Treviso",
"Trieste Friuli",
"Turin",
"Tel-Aviv",
"Terceira",
"Timisoara",
"Trabzon",
"Tampere-Pirkkala",
"Turku",
"Toulouse",
"Tivat",
"Trollhattan-Vanersborg",
"Tallinn",
"Tartu",
"Umea",
"Vienna",
"Varna",
"Volos",
"Valencia",
"Valladolid",
"Venice",
"Verona",
"Ventspils",
"Vilnius",
"Vagar",
"Vaxjo",
"Visby",
"Wangerooge",
"Weeze",
"Westerland",
"Wilhelmshaven",
"Warsaw",
"Wroclaw",
"Zweibruecken",
"Zaragoza",
"Zagreb",
"Zadar",
"Zurich",
"Chisinau",
"Minsk", 
"Gomel",
"Brest",
"Vitebsk",
"Grodna",
"Kiev",
"Kherson",
"Chernivtsi",
"Odesa",
"Zaporizhia",
"Vinnytsia",
"Lviv",
"Dnipro",
"Kharkiv",
"Ivano-Frankivsk",
"Moscow",
"St Petersburg", 
"Sochi",
"Novosibirsk", 
"Ekaterinburg", 
"Krasnodar",
"Anapa",
"Kaliningrad", 
"Platov",
"Samara", 
"Irkutsk", 
"Krasnoyarsk", 
"Ufa", 
"Kazan", 
"Mineralnye Vody", 
"Tyumen", 
"Khabarovsk", 
"Surgut", 
"Vladivostok", 
"Yakutsk",
"Perm", 
"Chelyabinsk", 
"Novy Urengoy", 
"Murmansk", 
"Nizhniy Novgorod", 
"Volgograd",
"Yuzhno-Sakhalinsk", 
"Arkhangelsk", 
"Omsk", 
"Makhachkala", 
"Gelendzik", 
"Petropavlovsk-Kamchatsky", 
"Naberezhnye Chelny", 
"Tomsk", 
"Nizhnevartovsk", 
"Orenburg", 
"Voronezh", 
"Syktyvkar", 
"Barnaul", 
"Astrakhan", 
"Norilsk", 
"Belgorod", 
"Salehard", 
"Chita", 
"Izhevsk", 
"Khanty-Mansiysk", 
"Saratov", 
"Stavropol", 
"Baikal", 
"Magadan", 
"Kemerovo", 
"Abakan", 
"Grozny", 
"Novokuzinetsk", 
"Vladikavkaz", 
"Ulyanovsk", 
"Nojabrxsk", 
"Penza", 
"Saransk", 
"Nadym", 
"Magnitogorsk", 
"Rostov on Don", 
"Cheboksary", 
"Blagoveschensk", 
"Nalchik", 
"Cherepovets", 
"Magas", 
"Kirov", 
"Naryan-Mar", 
"Bratsk", 
"Elista", 
"Gorno-Altaysk", 
"Talakan", 
"Tambov", 
"Vorkuta", 
"Neryungri", 
"Ivanovo", 
"Anadyr", 
"Kursk", 
"Kogalym", 
"Kurgan", 
"Petrozavodsk", 
"Orsk", 
"Polyarnyj", 
"Kaluga", 
"Okha", 
"Briansk", 
"Strzhewoi", 
"Kyzyl", 
"Tiksi", 
"Yaroslavl", 
"Pevek", 
"Solovetsky", 
"Velikij Ustyug", 
"Aldan", 
"Mirny", 
"Beloyarsky", 
"Bodaybo", 
"Ust-Kut", 
"Usinsk", 
"Nyagan", 
"Sabetta International", 
"Lensk", 
"Batagay", 
"Uraj", 
"Nikolaevsk-na-Amure", 
"Berezovo", 
"Bugulma", 
"Moma", 
"Sovetsky", 
"Olyokminsk", 
"Belaya Gora", 
"Mendeleyevo", 
"Srednekolymsk", 
"Lipetsk", 
"Nyurba", 
"Zyryanka", 
"Ust-Maya", 
"Iturup", 
"Kirensk", 
"Keperveyem", 
"Deputatsky", 
"Turukhansk", 
"Ust-Nera", 
"Saskylakh", 
"Terney", 
"Olenyok", 
"Cherskiy", 
"Kavalerovo", 
"Igarka", 
"Igrim", 
"Sakkyryr", 
"Ust-Kuyga", 
"Hatanga", 
"Dalnegorsk", 
"Nogliki", 
"Chokurdah", 
"Severo-Evensk", 
"Yerbogachen", 
"Tynda", 
"Preobrazheniye", 
"Podkamennaya Tunguska", 
"Zhigansk", 
"Dikson", 
"Verkhnevilyuysk", 
"Vilyuysk", 
"Dalnerechensk", 
"Svetlaya", 
"Komsomolsk Na Amure", 
"Teply Klyuch", 
"Bogorodskoye", 
"Plastun", 
"Kotlas", 
"Amgu", 
"Yedinka", 
"Joshkar-Ola", 
"Ukhta", 
"Shakhtyorsk", 
"Suntar" 
]
function createTableId(){
    var html = '<table class="id_cities"><thead><tr><th> id_city </th><th> name_city </th></tr></thead>';
    for (var i=0; i<cities.length; i++){
        html+= '<tr>';
        html += '<td>' + id_c + '</td><td>' + cities[i] + '</td>';
        //array_cities.push({id:id_c,city:cities[i]});
        html += '</tr>';
        id_c++;
    }
    html += "</table>";
    document.getElementById("cities_table").innerHTML = html;
    //console.log(array_cities);
    //localStorage.setItem("array_cities", JSON.stringify(array_cities));
    //var cart = JSON.parse(localStorage.getItem("array_cities"));
    //console.log(cart); 
}
createTableId();

export function createArrayId(){
    var array_cities = [];
    for (var i=0; i<cities.length; i++){
        array_cities.push({id:id_c,city:cities[i]});
        id_c++;
    }
    //localStorage.setItem("array_cities", JSON.stringify(array_cities));
    return array_cities;
}

// var html = '<table class="blueTable"><thead><tr><th>Name</th><th>Phone</th><th>Grade</th><th>Address</th><th>Delete</th></tr></thead>';
//     for(var i = 0; i < obj.length ; i++){
//         html += '<tr>';
//         html += '<td>' + obj[i].name + '</td><td>' + obj[i].phone + '</td><td>' + obj[i].grade + '</td><td>' + obj[i].address + '</td>';
//         html += '<td><div class="clear" onclick="Delete('+i+')">X</div></td>';
//         html += '</tr>';
//     }
//     html += "</table>";
//     document.getElementById("table").innerHTML = html;
// </script>

// </html>