const travelController = require("../controllers/travelController");

var cities = [
    "Ankara",
    "Antalya",
    "Banja Luka",
    "Barcelona",
    "Basel",
    "Belfast",
    "Belgrade",
    "Berlin",
    "Bern",
    "Birmingham",
    "Bologna",
    "Bordeaux",
    "Bratislava",
    "Bremen",
    "Brno",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Burgas",
    "Cambridge",
    "Chisinau",
    "Copenhagen",
    "Dnipro",
    "Dortmund",
    "Dresden",
    "Dublin",
    "Dubrovnik",
    "Duesseldorf",
    "Eilat",
    "Florence",
    "Frankfurt",
    "Gdansk",
    "Geneva",
    "Genoa",
    "Glasgow",
    "Granada",
    "Hamburg",
    "Hannover",
    "Helsinki",
    "Innsbruck",
    "Istanbul",
    "Karlovy Vary",
    "Kaunas",
    "Kharkiv",
    "Kiev",
    "Krakow",
    "Larnaca",
    "Lisbon",
    "Liverpool",
    "Ljubljana",
    "London",
    "Luxembourg",
    "Lviv",
    "Madrid",
    "Malaga",
    "Malmo",
    "Malta",
    "Manchester",
    "Milan",
    "Minsk", 
    "Monte Carlo",
    "Montpellier",
    "Moscow",
    "Munich",
    "Nantes",
    "Naples",
    "Nice",
    "Nuremberg",
    "Odesa",
    "Oslo",
    "Paris",
    "Pisa",
    "Porto",
    "Prague",
    "Pristina",
    "Reykjavik",
    "Rhodes",
    "Riga",
    "Rome",
    "Rotterdam",
    "Salzburg",
    "Sarajevo",
    "Sochi",
    "Sofia",
    "St Petersburg", 
    "Stockholm",
    "Strasbourg",
    "Tallinn",
    "Tel-Aviv",
    "Thessaloniki",
    "Tirana",
    "Tivat",
    "Turin",
    "Varna",
    "Venice",
    "Vienna",
    "Vilnius",
    "Warsaw",
    "Zagreb",
    "Zurich"     
]

var id_c=100;
var city_data={
    createArrayId:function (){
    //createArrayId(){    
    var array_cities = [];
    for (var i=0; i<cities.length; i++){
        array_cities.push({id:id_c,city:cities[i]});
        id_c++;
    }
    //travelController.insertCityToDB(array_cities);
    return array_cities;
    }
}

module.exports = city_data;
